/* Generated by Nim Compiler v0.13.1 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <stdio.h>
#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct {
N_NIMCALL_PTR(void, ClPrc) (void* x, void* ClEnv);
void* ClEnv;
} rtostask26006;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CLOSURE_PTR(void, TMP7) (void* x, void* ClEnv);
N_NIMCALL(void*, task_create)(rtostask26006 task, NimStringDesc* taskname, NU16 stacksize, NU32 priority);
N_NIMCALL(void, setuptask_27005)(void* params);
N_NIMCALL(void, usart_init)(NI usartno, NU32 baudrate);
N_NIMCALL(void, task_delete)(void* task);
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, start_scheduler)(void);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_rtosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_rtosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, mainInit000)(void);
NIM_EXTERNC N_NOINLINE(void, mainDatInit000)(void);
STRING_LITERAL(TMP6, "Hello world", 11);
STRING_LITERAL(TMP8, "Setup Task", 10);

static N_INLINE(void, nimFrame)(TFrame* s) {
}

static N_INLINE(void, popFrame)(void) {
}

N_NIMCALL(void, setuptask_27005)(void* params) {
	nimfr("setup_task", "main.nim")
	nimln(6, "main.nim");
	usart_init(((NI) 1), ((NU32) 115200));
	nimln(8, "main.nim");
	printf("%s\012", ((NimStringDesc*) &TMP6)? (((NimStringDesc*) &TMP6))->data:"nil");
	fflush(stdout);
	nimln(9, "main.nim");
	task_delete(NIM_NIL);
	popFrame();
}
void PreMainInner() {
	systemInit000();
	HEX00_rtosDatInit000();
	mainDatInit000();
	HEX00_rtosInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	mainInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	(*inner)();
}

int main(void) {
	NimMain();
	return 0;
}

NIM_EXTERNC N_NOINLINE(void, mainInit000)(void) {
	rtostask26006 LOC1;
	void* LOC2;
	nimfr("main", "main.nim")
	nimln(12, "main.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.ClPrc = ((TMP7) (setuptask_27005)); LOC1.ClEnv = NIM_NIL;
	LOC2 = 0;
	LOC2 = task_create(LOC1, ((NimStringDesc*) &TMP8), ((NU16) 100), ((NU32) 8));
	nimln(13, "main.nim");
	start_scheduler();
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, mainDatInit000)(void) {
}

