/* Generated by Nim Compiler v0.13.1 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
#define NIM_INTBITS 32

#include "nimbase.h"
static N_INLINE(void, nimFrame)(TFrame* s);
static N_INLINE(void, popFrame)(void);

static N_INLINE(void, nimFrame)(TFrame* s) {
}

static N_INLINE(void, popFrame)(void) {
}
NIM_EXTERNC N_NOINLINE(void, HEX00_rtosInit000)(void) {
	nimfr("rtos", "rtos.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, HEX00_rtosDatInit000)(void) {
}

